### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Kingdud** [OliverCardoza/dyson-sphere-graphviz#1]
https://github.com/OliverCardoza/dyson-sphere-graphviz/blob/f0c57b2f614745d04c3de9625e578d4d59f1085a/index.html#L123

titanium_allow should be titanium_alloy (nice tool btw)

**Comment by OliverCardoza** [comment]
Should be fixed now, ty for report!

**Comment by OliverCardoza** [comment]
Actually probably takes a few minutes for GitHub Pages cache to expire
